name: 'app: normalize params'
description: 'Normalizes optional params_json input into a JSON string.'

inputs:
  params_json:
    description: 'Raw JSON string (optional).'
    required: false

outputs:
  json:
    description: 'Normalized JSON string or {}.'
    value: ${{ steps.normalize.outputs.json }}

runs:
  using: 'composite'
  steps:
    - name: Normalize
      id: normalize
      shell: bash
      env:
        INPUT_PARAMS_JSON: ${{ inputs.params_json }}
      run: |
        set -euo pipefail
        J="${INPUT_PARAMS_JSON}"
        if [ -z "$J" ]; then J='{}'; fi
        {
          echo 'json<<EOF'
          printf '%s\n' "$J"
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
