outputs:
  env_name:
    description: 'Environment name (from build dispatch)'
    value: ${{ steps.bdisp.outputs.env_name }}
  env_key:
    description: 'Environment key (from build dispatch)'
    value: ${{ steps.bdisp.outputs.env_key }}
  image_tag:
    description: 'Image tag (from build dispatch)'
    value: ${{ steps.bdisp.outputs.image_tag }}
  deploy_enabled:
    description: 'Whether deployment is enabled (from build dispatch)'
    value: ${{ steps.bdisp.outputs.deploy_enabled }}
  new:
    description: 'New semantic version computed by version dispatch.'
    value: ${{ steps.vdisp.outputs.new }}
  major:
    description: 'Major alias (vX) computed by version dispatch.'
    value: ${{ steps.vdisp.outputs.major }}
  minor:
    description: 'Minor alias (vX.Y) computed by version dispatch.'
    value: ${{ steps.vdisp.outputs.minor }}
  last:
    description: 'Previous version tag reported by version dispatch.'
    value: ${{ steps.vdisp.outputs.last }}
  new_version:
    description: 'New semantic version computed by compute-next.'
    value: ${{ steps.vdisp.outputs.new }}
  major_version:
    description: 'Major alias (vX) computed by compute-next.'
    value: ${{ steps.vdisp.outputs.major }}
  minor_version:
    description: 'Minor alias (vX.Y) computed by compute-next.'
    value: ${{ steps.vdisp.outputs.minor }}
  last_version:
    description: 'Previous version tag reported by compute-next.'
    value: ${{ steps.vdisp.outputs.last }}
name: 'Uncover Actions'
description: 'Aggregator entrypoint to call sub-actions via a short ref: uncoverthefuture-org/actions@master'

inputs:
  subaction:
    description: "Sub-action to run (use 'help' or leave empty to list available)"
    required: false
  category:
    description: "Optional category to route: build | podman | infra | app (auto-derived from subaction if omitted)"
    required: false
  params_json:
    description: "JSON blob of parameters to pass to the selected subaction (keeps this file small)"
    required: false


runs:
  using: 'composite'
  steps:
    - name: Help (list available actions)
      if: ${{ !inputs.subaction || inputs.subaction == 'help' }}
      uses: uncoverthefuture-org/actions/.github/actions/common/print-help@master

    - name: Determine category
      id: route
      uses: uncoverthefuture-org/actions/.github/actions/common/route-category@master
      with:
        subaction: ${{ inputs.subaction }}
        category: ${{ inputs.category }}

    - name: Build dispatch
      id: bdisp
      if: ${{ steps.route.outputs.category == 'build' }}
      uses: uncoverthefuture-org/actions/.github/actions/build/dispatch@master
      with:
        subaction: ${{ inputs.subaction }}
        params_json: ${{ inputs.params_json }}

    - name: Podman dispatch
      if: ${{ steps.route.outputs.category == 'podman' }}
      uses: uncoverthefuture-org/actions/.github/actions/podman/dispatch@master
      with:
        subaction: ${{ inputs.subaction }}
        params_json: ${{ inputs.params_json }}

    - name: Infra dispatch
      if: ${{ steps.route.outputs.category == 'infra' }}
      uses: uncoverthefuture-org/actions/.github/actions/infra/dispatch@master
      with:
        subaction: ${{ inputs.subaction }}
        params_json: ${{ inputs.params_json }}

    - name: App dispatch
      if: ${{ steps.route.outputs.category == 'app' }}
      uses: uncoverthefuture-org/actions/.github/actions/app/dispatch@master
      with:
        subaction: ${{ inputs.subaction }}
        params_json: ${{ inputs.params_json }}

    - name: Version dispatch
      id: vdisp
      if: ${{ steps.route.outputs.category == 'version' }}
      uses: uncoverthefuture-org/actions/.github/actions/version/dispatch@master
      with:
        subaction: ${{ inputs.subaction }}
        params_json: ${{ inputs.params_json }}
