name: 'app: summary/resources'
description: 'Capture Podman resource usage statistics.'

# This sub-action extracts resource monitoring logic from deployment-status-summary.
# It queries the remote host via SSH to collect:
# - Podman version
# - Pod listings
# - Network listings
# - Network listeners (ss/netstat)
# - Resource usage via podman stats
# Example usage:
#   - uses: ./.github/actions/app/summary/resources
#     with:
#       ssh_host: ${{ secrets.SERVER_HOST }}
#       ssh_user: ${{ secrets.SERVER_USER }}
#       ssh_key: ${{ secrets.SERVER_SSH_KEY }}

inputs:
  ssh_host:
    description: 'Remote SSH host'
    required: true
  ssh_user:
    description: 'SSH username'
    required: true
  ssh_key:
    description: 'SSH private key'
    required: true
  ssh_port:
    description: 'SSH port'
    required: false
    default: '22'
  container_name:
    description: 'Container name for stats (optional)'
    required: false
    default: ''

outputs:
  podman_version:
    description: 'Podman version string'
    value: ${{ steps.resources.outputs.podman_version }}
  pods_table:
    description: 'Podman pods listing'
    value: ${{ steps.resources.outputs.pods_table }}
  networks_table:
    description: 'Podman networks listing'
    value: ${{ steps.resources.outputs.networks_table }}
  listeners:
    description: 'Network listeners (ss/netstat output)'
    value: ${{ steps.resources.outputs.listeners }}
  stats_table:
    description: 'Podman stats snapshot'
    value: ${{ steps.resources.outputs.stats_table }}

runs:
  using: 'composite'
  steps:
    - name: Capture resource stats
      id: resources
      shell: bash
      env:
        SSH_HOST: ${{ inputs.ssh_host }}
        SSH_USER: ${{ inputs.ssh_user }}
        SSH_KEY: ${{ inputs.ssh_key }}
        SSH_PORT: ${{ inputs.ssh_port }}
        CONTAINER_NAME: ${{ inputs.container_name }}
      run: |
        set -uo pipefail

        # Prepare SSH key file
        KEY_FILE="$(mktemp)"
        trap "rm -f '$KEY_FILE'" EXIT
        if printf '%s' "$SSH_KEY" | grep -q '\\n'; then
          printf '%s\n' "$SSH_KEY" | sed 's/\\n/\n/g' > "$KEY_FILE"
        else
          printf '%s\n' "$SSH_KEY" > "$KEY_FILE"
        fi
        chmod 600 "$KEY_FILE"

        # SSH base command with timeout and connection settings
        SSH_BASE=(ssh -i "$KEY_FILE" -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=8 -p "${SSH_PORT:-22}" "${SSH_USER}@${SSH_HOST}")

        # Gather resource information
        PODMAN_VERSION="$(${SSH_BASE[@]} 'podman --version' 2>/dev/null || echo "unavailable")"
        PODS_TBL="$(${SSH_BASE[@]} "podman pod ps -a --format 'table {{.ID}}\t{{.Status}}\t{{.Name}}\t{{.Networks}}'" 2>/dev/null || echo "unavailable")"
        NETWORKS_TBL="$(${SSH_BASE[@]} "podman network ls --format 'table {{.Name}}\t{{.Driver}}\t{{.Labels}}'" 2>/dev/null || echo "unavailable")"
        LISTENERS="$(${SSH_BASE[@]} "ss -ltnp 2>/dev/null | head -n 80 || netstat -ltnp 2>/dev/null | head -n 80" 2>/dev/null || echo "unavailable")"

        # Gather stats: if container_name provided, stats for that container; otherwise all containers
        STATS_TBL="unavailable"
        if [ -n "$CONTAINER_NAME" ]; then
          STATS_TBL="$(${SSH_BASE[@]} "podman stats --no-stream '$CONTAINER_NAME' 2>/dev/null" || echo "unavailable")"
        else
          STATS_TBL="$(${SSH_BASE[@]} "podman stats --no-stream 2>/dev/null" || echo "unavailable")"
        fi

        # Output results (escaped for GitHub Actions)
        {
          echo "podman_version=$PODMAN_VERSION"
          echo "pods_table<<PODS_EOF"
          echo "$PODS_TBL"
          echo "PODS_EOF"
          echo "networks_table<<NETWORKS_EOF"
          echo "$NETWORKS_TBL"
          echo "NETWORKS_EOF"
          echo "listeners<<LISTENERS_EOF"
          echo "$LISTENERS"
          echo "LISTENERS_EOF"
          echo "stats_table<<STATS_EOF"
          echo "$STATS_TBL"
          echo "STATS_EOF"
        } >> "$GITHUB_OUTPUT"
