/**
 * GitHub Manager
 * Creates PRs for artifact setup (Dockerfile, artifact.json)
 * For the soobu-beauty-theme project
 */
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';
import type { ArtifactConfig } from '../types';
import { getLogger } from '../utils/logger';

const logger = getLogger();

export interface GitHubConfig {
  token?: string;
  username?: string;
  defaultRepo?: string;
  defaultBranch?: string;
}

export class GitHubManager {
  private config: GitHubConfig;
  private configPath: string;

  constructor(config?: GitHubConfig) {
    this.configPath = join(homedir(), '.uactions', 'github.json');
    this.config = config || this.loadConfig();
  }

  /**
   * Load GitHub config from file
   */
  private loadConfig(): GitHubConfig {
    try {
      if (existsSync(this.configPath)) {
        const content = readFileSync(this.configPath, 'utf-8');
        return JSON.parse(content);
      }
    } catch {
      // Ignore errors
    }
    return {
      defaultBranch: 'main',
    };
  }

  /**
   * Save GitHub config
   */
  saveConfig(): void {
    const configDir = join(homedir(), '.uactions');
    if (!existsSync(configDir)) {
      const { mkdirSync } = require('fs');
      mkdirSync(configDir, { recursive: true });
    }
    writeFileSync(this.configPath, JSON.stringify(this.config, null, 2));
  }

  /**
   * Set GitHub token
   */
  setToken(token: string): void {
    this.config.token = token;
    this.saveConfig();
  }

  /**
   * Check if authenticated
   */
  isAuthenticated(): boolean {
    return !!this.config.token;
  }

  /**
   * Generate a Dockerfile for a project
   */
  generateDockerfile(artifact: ArtifactConfig, projectType: 'php-laravel' | 'node' | 'static' | 'python' = 'static'): string {
    const port = artifact.container.port || 8080;
    
    switch (projectType) {
      case 'php-laravel':
        return this.generateLaravelDockerfile(port);
      case 'node':
        return this.generateNodeDockerfile(port);
      case 'python':
        return this.generatePythonDockerfile(port);
      case 'static':
      default:
        return this.generateStaticDockerfile(port);
    }
  }

  /**
   * Generate Laravel/PHP Dockerfile
   */
  private generateLaravelDockerfile(port: number): string {
    return `# Laravel/PHP Application Dockerfile
# Generated by UActions

FROM php:8.2-apache

# Install system dependencies
RUN apt-get update && apt-get install -y \\
    git \\
    curl \\
    libpng-dev \\
    libonig-dev \\
    libxml2-dev \\
    zip \\
    unzip \\
    nodejs \\
    npm

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/html

# Copy application
COPY . .

# Install dependencies
RUN composer install --no-dev --optimize-autoloader

# Set permissions
RUN chown -R www-data:www-data /var/www/html \\
    && chmod -R 755 /var/www/html/storage

# Configure Apache
RUN echo "ServerName localhost" >> /etc/apache2/conf-available/servername.conf \\
    && a2enconf servername \\
    && a2enmod rewrite

# Update Apache port
RUN sed -i "s/80/${port}/g" /etc/apache2/sites-available/000-default.conf \\
    && sed -i "s/80/${port}/g" /etc/apache2/ports.conf

EXPOSE ${port}

CMD ["apache2-foreground"]
`;
  }

  /**
   * Generate Node.js Dockerfile
   */
  private generateNodeDockerfile(port: number): string {
    return `# Node.js Application Dockerfile
# Generated by UActions

FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy application
COPY . .

# Build if build script exists
RUN if [ -f "package.json" ] && grep -q '"build"' package.json; then npm run build; fi

EXPOSE ${port}

USER node

CMD ["node", "server.js"]
`;
  }

  /**
   * Generate Python Dockerfile
   */
  private generatePythonDockerfile(port: number): string {
    return `# Python Application Dockerfile
# Generated by UActions

FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application
COPY . .

EXPOSE ${port}

CMD ["python", "app.py"]
`;
  }

  /**
   * Generate Static Site Dockerfile
   */
  private generateStaticDockerfile(port: number): string {
    return `# Static Site Dockerfile
# Generated by UActions

FROM nginx:alpine

# Copy static files
COPY . /usr/share/nginx/html

# Create custom nginx config
RUN echo 'server { \\
    listen ${port}; \\
    server_name localhost; \\
    root /usr/share/nginx/html; \\
    index index.html index.htm; \\
    location / { \\
        try_files \\$uri \\$uri/ /index.html; \\
    } \\
    gzip on; \\
    gzip_types text/plain text/css application/json application/javascript; \\
}' > /etc/nginx/conf.d/default.conf

EXPOSE ${port}

CMD ["nginx", "-g", "daemon off;"]
`;
  }

  /**
   * Create a GitHub PR for the artifact setup
   * This is a mock implementation - in production, this would use the GitHub API
   */
  async createArtifactPR(
    artifact: ArtifactConfig,
    projectPath: string,
    projectType: 'php-laravel' | 'node' | 'static' | 'python' = 'static'
  ): Promise<{ success: boolean; prUrl?: string; error?: string }> {
    if (!this.isAuthenticated()) {
      return {
        success: false,
        error: 'GitHub token not configured. Run: uactions github login',
      };
    }

    const repo = artifact.github?.repo || this.config.defaultRepo;
    if (!repo) {
      return {
        success: false,
        error: 'No repository specified in artifact or config',
      };
    }

    // Generate Dockerfile
    const dockerfile = this.generateDockerfile(artifact, projectType);
    const dockerfilePath = join(projectPath, 'Dockerfile');

    // Save Dockerfile locally
    writeFileSync(dockerfilePath, dockerfile);
    logger.success(`Created Dockerfile at ${dockerfilePath}`);

    // Save artifact.json
    const artifactPath = join(projectPath, 'artifact.json');
    writeFileSync(artifactPath, JSON.stringify(artifact, null, 2));
    logger.success(`Created artifact.json at ${artifactPath}`);

    // In a real implementation, this would:
    // 1. Create a new branch
    // 2. Commit the Dockerfile and artifact.json
    // 3. Push to GitHub
    // 4. Create a PR
    // For now, we return instructions

    const branch = `uactions/setup-${artifact.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}`;
    
    logger.info(`
To create a PR with the UActions setup:

1. Stage the new files:
   cd ${projectPath}
   git add Dockerfile artifact.json

2. Create a new branch and commit:
   git checkout -b ${branch}
   git commit -m "Add UActions deployment configuration"
   git push origin ${branch}

3. Create a PR via GitHub CLI or web interface
`);

    return {
      success: true,
      prUrl: `https://github.com/${repo}/compare/${artifact.github?.branch || 'main'}...${branch}`,
    };
  }

  /**
   * Get GitHub CLI instructions
   */
  getCLIInstructions(): string {
    return `
# GitHub Integration Setup

## Option 1: GitHub CLI (Recommended)
1. Install gh: https://cli.github.com/
2. Authenticate: gh auth login
3. Create PRs automatically: uactions deploy --create-pr

## Option 2: Personal Access Token
1. Go to https://github.com/settings/tokens
2. Create token with 'repo' scope
3. Run: uactions github login --token YOUR_TOKEN

## Current Configuration
Config file: ${this.configPath}
Authenticated: ${this.isAuthenticated() ? 'Yes' : 'No'}
${this.config.defaultRepo ? `Default repo: ${this.config.defaultRepo}` : ''}
`;
  }
}
