name: 'infra: install-apache'
description: 'Install Apache2 and enable modules on Ubuntu/Debian host'

inputs:
  ssh_host:
    description: 'SSH host'
    required: true
  ssh_user:
    description: 'SSH username (non-root)'
    required: true
  ssh_key:
    description: 'SSH private key for non-root user'
    required: true
  root_ssh_key:
    description: 'SSH private key for root (optional)'
    required: false
  ssh_port:
    description: 'SSH port'
    required: false
    default: '22'
  ssh_fingerprint:
    description: 'Server SSH host key fingerprint'
    required: false
  podman_user:
    description: 'User on remote host'
    required: false
    default: 'deployer'
  connect_mode:
    description: "How to connect: 'auto' (default), 'root', or 'user'"
    required: false
    default: 'auto'

runs:
  using: 'composite'
  steps:
    - name: Install Apache2
      uses: uncoverthefuture-org/actions/.github/actions/podman/remote-podman-exec@v1.0.27
      with:
        ssh_host: ${{ inputs.ssh_host }}
        ssh_user: ${{ inputs.ssh_user }}
        ssh_key: ${{ inputs.ssh_key }}
        root_ssh_key: ${{ inputs.root_ssh_key }}
        ssh_port: ${{ inputs.ssh_port }}
        ssh_fingerprint: ${{ inputs.ssh_fingerprint }}
        podman_user: ${{ inputs.podman_user }}
        connect_mode: ${{ inputs.connect_mode }}
        source_env: 'false'
        fail_if_env_missing: 'false'
        inline_script: |
          set -euo pipefail
          apt-get update -y
          apt-get install -y apache2 libapache2-mod-wsgi-py3
          a2enmod headers proxy proxy_http proxy_uwsgi wsgi || true
          systemctl enable apache2 || true
          systemctl restart apache2 || true
