name: 'infra: configure-ufw'
description: 'Configure UFW firewall on Ubuntu/Debian host'

inputs:
  ssh_host:
    description: 'SSH host'
    required: true
  ssh_user:
    description: 'SSH username (non-root)'
    required: true
  ssh_key:
    description: 'SSH private key for non-root user'
    required: true
  root_ssh_key:
    description: 'SSH private key for root (optional)'
    required: false
  ssh_port:
    description: 'SSH port'
    required: false
    default: '22'
  ssh_fingerprint:
    description: 'Server SSH host key fingerprint'
    required: false
  podman_user:
    description: 'User on remote host'
    required: false
    default: 'deployer'
  connect_mode:
    description: "How to connect: 'auto' (default), 'root', or 'user'"
    required: false
    default: 'auto'
  ufw_allow_ports:
    description: 'Space/newline-separated list of ports to allow'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Configure UFW
      uses: uncoverthefuture-org/actions/.github/actions/podman/remote-podman-exec@v1.0.26
      with:
        ssh_host: ${{ inputs.ssh_host }}
        ssh_user: ${{ inputs.ssh_user }}
        ssh_key: ${{ inputs.ssh_key }}
        root_ssh_key: ${{ inputs.root_ssh_key }}
        ssh_port: ${{ inputs.ssh_port }}
        ssh_fingerprint: ${{ inputs.ssh_fingerprint }}
        podman_user: ${{ inputs.podman_user }}
        connect_mode: ${{ inputs.connect_mode }}
        source_env: 'false'
        fail_if_env_missing: 'false'
        inline_script: |
          set -euo pipefail
          apt-get install -y ufw || true
          ufw --force enable || true
          for p in ${{ inputs.ufw_allow_ports }}; do
            ufw allow "$p"/tcp || true
          done
          ufw status || true
