name: 'infra: configure-ufw'
description: 'Configure UFW firewall on Ubuntu/Debian host'

inputs:
  ssh_host:
    description: 'SSH host'
    required: true
  ssh_user:
    description: 'SSH username (non-root)'
    required: true
  ssh_key:
    description: 'SSH private key for non-root user'
    required: true
  root_ssh_key:
    description: 'SSH private key for root (optional)'
    required: false
  ssh_port:
    description: 'SSH port'
    required: false
    default: '22'
  ssh_fingerprint:
    description: 'Server SSH host key fingerprint'
    required: false
  podman_user:
    description: 'User on remote host (not used for UFW, kept for consistency)'
    required: false
    default: ''
  connect_mode:
    description: "How to connect: 'auto' (default), 'root', or 'user'"
    required: false
    default: 'auto'
  ufw_allow_ports:
    description: 'Space-separated list of ports to allow (e.g., "80 443 22")'
    required: false
    default: ''
  enable_podman_forward:
    description: 'Enable ufw route allow for WAN->Podman bridge ports'
    required: false
    default: 'true'
  route_ports:
    description: 'Space-separated list of ports to forward (e.g., "80 443")'
    required: false
    default: '80 443'
  set_forward_policy_accept:
    description: 'Set DEFAULT_FORWARD_POLICY="ACCEPT" in /etc/default/ufw'
    required: false
    default: 'true'
  wan_iface:
    description: 'Override WAN interface name (auto-detect if empty)'
    required: false
    default: ''
  podman_iface:
    description: 'Override Podman bridge interface name (auto-detect if empty)'
    required: false
    default: ''
  skip_upload:
    description: 'Skip staging/upload (assumes scripts deployed via deploy-server-scripts)'
    required: false
    default: 'true'
  show_root_install_hints:
    description: 'Show explicit manual install instructions when root privileges are required (fail-fast messaging)'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    # Probe: Check SSH reachability to avoid scp timeouts
    - name: Check SSH reachability
      id: reach
      shell: bash
      env:
        SSH_HOST: ${{ inputs.ssh_host }}
        SSH_USER: ${{ inputs.ssh_user }}
        SSH_KEY: ${{ inputs.ssh_key }}
        SSH_PORT: ${{ inputs.ssh_port }}
      run: |
        set -euo pipefail
        KEY_FILE="$(mktemp)"
        trap "rm -f '$KEY_FILE'" EXIT
        if printf '%s' "$SSH_KEY" | grep -q '\\n'; then
          printf '%s\n' "$SSH_KEY" | sed 's/\\n/\n/g' > "$KEY_FILE"
        else
          printf '%s\n' "$SSH_KEY" > "$KEY_FILE"
        fi
        chmod 600 "$KEY_FILE"
        if ssh -i "$KEY_FILE" -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=8 -p "${SSH_PORT:-22}" "$SSH_USER@$SSH_HOST" true 2>/dev/null; then
          echo "reachable=true" >> "$GITHUB_OUTPUT"
        else
          echo "reachable=false" >> "$GITHUB_OUTPUT"
        fi
    - name: Fail fast if cannot escalate for UFW configuration
      if: ${{ steps.reach.outputs.reachable == 'true' && inputs.connect_mode != 'root' }}
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ inputs.ssh_host }}
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_key }}
        port: ${{ inputs.ssh_port }}
        fingerprint: ${{ inputs.ssh_fingerprint }}
        script: |
          set -euo pipefail
          if [ "$(id -u)" -eq 0 ]; then exit 0; fi
          if command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then exit 0; fi
          if [ '${{ inputs.show_root_install_hints }}' = 'true' ]; then
            echo '::error::UFW configuration requires root privileges; current session cannot escalate.' >&2
            echo "Detected: user=$(id -un); sudo(non-interactive)=no" >&2
            echo 'Install manually on the server (as root), then re-run:' >&2
            echo '  sudo apt-get update -y' >&2
            echo '  sudo apt-get install -y ufw' >&2
            echo '  sudo ufw --force enable' >&2
            echo '  sudo ufw allow 22/tcp   # plus any ports you need' >&2
            echo 'Or re-run this action with connect_mode: root (or provide root_ssh_key).' >&2
          else
            echo '::error::Root privileges required to configure UFW.' >&2
          fi
          exit 1
    # Stage: Copy script from action path to workspace
    - name: Stage configure-ufw script
      if: ${{ steps.reach.outputs.reachable == 'true' && inputs.skip_upload != 'true' }}
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        WORKSPACE: ${{ github.workspace }}
      run: |
        set -euo pipefail
        mkdir -p "$WORKSPACE/.uactions_cache"
        cp "$ACTION_PATH/../../scripts/infra/configure-ufw.sh" "$WORKSPACE/.uactions_cache/configure-ufw.sh"

    # Upload: Transfer script to remote /tmp via scp
    - name: Upload configure-ufw script
      if: ${{ steps.reach.outputs.reachable == 'true' && inputs.skip_upload != 'true' }}
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.ssh_host }}
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_key }}
        port: ${{ inputs.ssh_port }}
        source: ".uactions_cache/configure-ufw.sh"
        target: "/tmp"
        overwrite: true
        timeout: 15s
        command_timeout: 30s

    # Execute: Move to $HOME/uactions/scripts/, chmod, export env, run
    - name: Execute configure-ufw
      if: ${{ steps.reach.outputs.reachable == 'true' }}
      uses: ./.github/actions/podman/remote-podman-exec
      with:
        ssh_host: ${{ inputs.ssh_host }}
        ssh_user: ${{ inputs.ssh_user }}
        ssh_key: ${{ inputs.ssh_key }}
        root_ssh_key: ${{ inputs.root_ssh_key }}
        ssh_port: ${{ inputs.ssh_port }}
        ssh_fingerprint: ${{ inputs.ssh_fingerprint }}
        podman_user: ${{ inputs.podman_user }}
        connect_mode: ${{ inputs.connect_mode }}
        source_env: 'false'
        fail_if_env_missing: 'false'
        inline_script: |
          set -euo pipefail
          mkdir -p "$HOME/uactions/scripts/infra"
          if [ -f /tmp/configure-ufw.sh ]; then
            mv -f /tmp/configure-ufw.sh "$HOME/uactions/scripts/infra/configure-ufw.sh"
          fi
          chmod +x "$HOME/uactions/scripts/infra/configure-ufw.sh"

          export SSH_PORT='${{ inputs.ssh_port }}'
          export UFW_ALLOW_PORTS='${{ inputs.ufw_allow_ports }}'
          export ENABLE_PODMAN_FORWARD='${{ inputs.enable_podman_forward }}'
          export ROUTE_PORTS='${{ inputs.route_ports }}'
          export SET_FORWARD_POLICY_ACCEPT='${{ inputs.set_forward_policy_accept }}'
          export WAN_IFACE='${{ inputs.wan_iface }}'
          export PODMAN_IFACE='${{ inputs.podman_iface }}'

          if [ "$(id -u)" -ne 0 ] && command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
            sudo env \
              SSH_PORT="$SSH_PORT" \
              UFW_ALLOW_PORTS="$UFW_ALLOW_PORTS" \
              ENABLE_PODMAN_FORWARD="$ENABLE_PODMAN_FORWARD" \
              ROUTE_PORTS="$ROUTE_PORTS" \
              SET_FORWARD_POLICY_ACCEPT="$SET_FORWARD_POLICY_ACCEPT" \
              WAN_IFACE="$WAN_IFACE" \
              PODMAN_IFACE="$PODMAN_IFACE" \
              "$HOME/uactions/scripts/infra/configure-ufw.sh"
          else
            "$HOME/uactions/scripts/infra/configure-ufw.sh"
          fi
