name: 'infra: deploy-server-scripts'
description: 'Bundle and deploy all server-managed scripts to $HOME/uactions/scripts on the remote host (run once before any other steps).'

inputs:
  ssh_host:
    description: 'SSH host'
    required: true
  ssh_user:
    description: 'SSH username'
    required: true
  ssh_key:
    description: 'SSH private key'
    required: true
  ssh_port:
    description: 'SSH port'
    required: false
    default: '22'
  ssh_fingerprint:
    description: 'SSH host key fingerprint'
    required: false

runs:
  using: 'composite'
  steps:
    # Probe: Check SSH reachability to avoid noisy timeouts
    - name: Check SSH reachability
      id: reach
      shell: bash
      env:
        SSH_HOST: ${{ inputs.ssh_host }}
        SSH_USER: ${{ inputs.ssh_user }}
        SSH_KEY: ${{ inputs.ssh_key }}
        SSH_PORT: ${{ inputs.ssh_port }}
      run: |
        set -euo pipefail
        KEY_FILE="$(mktemp)"
        trap "rm -f '$KEY_FILE'" EXIT
        if printf '%s' "$SSH_KEY" | grep -q '\\n'; then
          printf '%s\n' "$SSH_KEY" | sed 's/\\n/\n/g' > "$KEY_FILE"
        else
          printf '%s\n' "$SSH_KEY" > "$KEY_FILE"
        fi
        chmod 600 "$KEY_FILE"
        ok=false
        for i in 1 2 3; do
          if ssh -i "$KEY_FILE" -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=8 -p "${SSH_PORT:-22}" "$SSH_USER@$SSH_HOST" true 2>/dev/null; then
            ok=true; break
          fi
          sleep 5
        done
        if $ok; then echo "reachable=true" >> "$GITHUB_OUTPUT"; else echo "reachable=false" >> "$GITHUB_OUTPUT"; fi
    # Stage: Tar up the entire scripts directory into workspace cache
    - name: Stage scripts bundle
      id: stage
      if: ${{ steps.reach.outputs.reachable == 'true' }}
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        WORKSPACE: ${{ github.workspace }}
      run: |
        set -euo pipefail
        mkdir -p "$WORKSPACE/.uactions_cache"
        TAR_PATH="$WORKSPACE/.uactions_cache/uactions-scripts.tgz"
        SRC_ROOT="$(cd "$ACTION_PATH/../.." && pwd)"
        if [ ! -d "$SRC_ROOT/scripts" ]; then
          echo '::notice::No local scripts directory found; skipping server scripts upload.'
          echo "has_bundle=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        tar -C "$SRC_ROOT" -czf "$TAR_PATH" scripts
        # Validate archive locally before upload
        if ! tar -tzf "$TAR_PATH" >/dev/null 2>&1; then
          echo '::error::Staged tarball appears invalid or empty (tar -tzf failed). Aborting upload.'
          ls -lh "$TAR_PATH" || true
          exit 1
        fi
        ls -lh "$TAR_PATH"
        echo "has_bundle=true" >> "$GITHUB_OUTPUT"

    # Upload: Transfer tarball to remote /tmp via scp
    - name: Upload scripts bundle
      id: upload
      if: ${{ steps.reach.outputs.reachable == 'true' && steps.stage.outputs.has_bundle == 'true' }}
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.ssh_host }}
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_key }}
        port: ${{ inputs.ssh_port }}
        source: ".uactions_cache/uactions-scripts.tgz"
        target: "~"
        overwrite: true
        strip_components: 1
        timeout: 15s
        command_timeout: 30s

    # Execute: Extract into $HOME/uactions, set executable bits, stamp version
    - name: Install scripts on remote host
      if: ${{ steps.reach.outputs.reachable == 'true' && steps.stage.outputs.has_bundle == 'true' && steps.upload.outcome == 'success' }}
      uses: ./.github/actions/podman/remote-podman-exec
      with:
        ssh_host: ${{ inputs.ssh_host }}
        ssh_user: ${{ inputs.ssh_user }}
        ssh_key: ${{ inputs.ssh_key }}
        ssh_port: ${{ inputs.ssh_port }}
        ssh_fingerprint: ${{ inputs.ssh_fingerprint }}
        # Remote execution runs strictly as ssh_user to avoid implicit user switching.
        connect_mode: user
        source_env: 'false'
        fail_if_env_missing: 'false'
        inline_script: |
          set -euo pipefail
          mkdir -p "$HOME/uactions"
          if [ ! -f "$HOME/uactions-scripts.tgz" ]; then
            echo '::error::Missing $HOME/uactions-scripts.tgz on remote host (upload failed or was skipped)';
            exit 1
          fi
          # Validate tarball integrity to avoid 'tar: empty archive'
          if ! tar -tzf "$HOME/uactions-scripts.tgz" >/dev/null 2>&1; then
            echo '::error::Invalid or empty tar archive at $HOME/uactions-scripts.tgz (tar -tzf failed)';
            ls -lh "$HOME/uactions-scripts.tgz" || true
            exit 1
          fi
          # Replace scripts atomically
          TMPDIR="$(mktemp -d)"
          tar -xzf "$HOME/uactions-scripts.tgz" -C "$TMPDIR"
          rm -rf "$HOME/uactions/scripts"
          mv "$TMPDIR/scripts" "$HOME/uactions/scripts"
          rm -rf "$TMPDIR"
          # Ensure all scripts are executable
          find "$HOME/uactions/scripts" -type f -name '*.sh' -exec chmod +x {} +
          # Stamp version marker for visibility
          date -u +'%Y-%m-%d %H:%M:%S UTC' > "$HOME/uactions/scripts/.deployed_at"
          echo '${{ github.sha }}' > "$HOME/uactions/scripts/.version"

    - name: Skip notice (host unreachable)
      if: ${{ steps.reach.outputs.reachable != 'true' }}
      shell: bash
      run: |
        echo '::notice::SSH host not reachable; skipped deploying server scripts.'
