name: 'infra: compute-host-port'
description: 'Compute the host port to proxy to, either from explicit input or env file'

inputs:
  ssh_host:
    description: 'SSH host'
    required: true
  ssh_user:
    description: 'SSH username (non-root)'
    required: true
  ssh_key:
    description: 'SSH private key for non-root user'
    required: true
  root_ssh_key:
    description: 'SSH private key for root (optional)'
    required: false
  ssh_port:
    description: 'SSH port'
    required: false
    default: '22'
  ssh_fingerprint:
    description: 'Server SSH host key fingerprint'
    required: false
  podman_user:
    description: 'User on remote host'
    required: false
    default: ''
  connect_mode:
    description: "How to connect: 'auto' (default), 'root', or 'user'"
    required: false
    default: 'auto'
  env_name:
    description: 'Environment name'
    required: false
  env_file_path:
    description: 'Base path to the environment file'
    required: false
  source_env:
    description: 'Source env file to derive HOST_PORT'
    required: false
    default: 'true'
  host_port:
    description: 'Explicit host port to use'
    required: false

outputs:
  host_port:
    description: 'The computed host port'
    value: ${{ steps.compute.outputs.host_port }}

runs:
  using: 'composite'
  steps:
    # Execute locally: run compute script and write to GITHUB_OUTPUT
    - name: Compute host port
      id: compute
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        HOST_PORT_IN: ${{ inputs.host_port }}
        ENV_NAME: ${{ inputs.env_name }}
      run: |
        set -euo pipefail
        bash "$ACTION_PATH/../../scripts/infra/compute-host-port.sh"
