# ============================================================================
# ACTION: Lint Uses
# ============================================================================
# PURPOSE:
# Validates action reference patterns in YAML files.
# Ensures consistent use of relative vs repository references.
#
# WHAT IT DOES:
# 1. Scans YAML files for action uses
# 2. Validates reference patterns
# 3. Checks for forbidden patterns
# 4. Reports violations
#
# WHEN TO USE:
# - Validate action references
# - Enforce reference patterns
# - Part of CI/CD validation
#
# REFERENCE: See docs/ACTION_FILES_GUIDE.md for complete guide
# ============================================================================

name: 'common: lint-uses'
description: 'Reusable lint to ensure allowed action reference patterns (relative vs deep repo)'

# ============================================================================
# INPUTS
# ============================================================================
inputs:
  allow_deep_repo:
    description: 'Allow deep repository uses. Default: true'
    required: false
    default: 'true'

# ============================================================================
# EXECUTION STEPS
# ============================================================================
runs:
  using: 'composite'
  steps:
    # ========================================================================
    # STEP 1: Lint action uses
    # ========================================================================
    # Validates action reference patterns
    # ========================================================================
    - name: Lint action uses
      shell: bash
      run: |
        set -euo pipefail
        echo "Checking for forbidden uses..."
        # Check for relative uses outside version actions
        REL_FILES=$(find . -name "*.yml" -o -name "*.yaml" \
          | grep -v action.yml \
          | xargs grep -lE "^[[:space:]]*uses:[[:space:]]+\./\\.github/actions/" \
          | grep -v "/auto-version.yml$" \
          | grep -v "version/compute-next" \
          | grep -v "version/update-tags" || true)
        if [ -n "$REL_FILES" ]; then
          echo "::error::Found relative uses in: $REL_FILES"
          echo "Error: Found relative uses in: $REL_FILES" >&2
          exit 1
        fi

        if [ "${{ inputs.allow_deep_repo }}" = "false" ]; then
          # Check for deep repo uses (disabled by default)
          DEEP_FILES=$(find . -name "*.yml" -o -name "*.yaml" \
            | grep -v README.md \
            | grep -v "^\./action\.yml$" \
            | grep -v "\.github/actions/version/dispatch/action.yml" \
            | xargs grep -lE "^[[:space:]]*uses:[[:space:]]+uncoverthefuture-org/actions/\\.github/actions/" || true)
          if [ -n "$DEEP_FILES" ]; then
            echo "::error::Found deep repo uses in: $DEEP_FILES"
            echo "Error: Found deep repo uses in: $DEEP_FILES" >&2
            exit 1
          fi
        fi

        echo "Lint passed."
