# ============================================================================
# ACTION: Update Tags
# ============================================================================
# PURPOSE:
# Creates new version tag and updates major/minor alias tags in git.
# Used to maintain semantic version tags for releases.
#
# WHAT IT DOES:
# 1. Validates tag format (vX.Y.Z, vX.Y, vX)
# 2. Creates new full version tag if missing
# 3. Updates major alias tag to point to new version
# 4. Updates minor alias tag to point to new version
# 5. Pushes all tags to repository
#
# WHEN TO USE:
# - Create git tags for new releases
# - Update version aliases (v1, v1.0)
# - Part of release automation
#
# REFERENCE: See docs/ACTION_FILES_GUIDE.md for complete guide
# ============================================================================

name: 'version: update-tags'
description: 'Create the new version tag if missing, and (force) update major/minor alias tags to point to it.'

# ============================================================================
# INPUTS
# ============================================================================
inputs:
  new:
    description: 'New full version tag (vX.Y.Z). Required. Example: v1.2.3'
    required: true
  major:
    description: 'Major alias tag (vX). Required. Example: v1'
    required: true
  minor:
    description: 'Minor alias tag (vX.Y). Required. Example: v1.2'
    required: true
  tag_message:
    description: 'Message for annotated tags. Optional. Default: empty (lightweight tags)'
    required: false
    default: ''

# ============================================================================
# EXECUTION STEPS
# ============================================================================
runs:
  using: 'composite'
  steps:
    # ========================================================================
    # STEP 1: Validate tag inputs
    # ========================================================================
    # Ensures all tags are in correct format
    # ========================================================================
    - name: Validate tag inputs
      shell: bash
      env:
        NEW: ${{ inputs.new }}
        MAJOR: ${{ inputs.major }}
        MINOR: ${{ inputs.minor }}
      run: |
        set -euo pipefail
        for var in NEW MAJOR MINOR; do
          value="${!var}"
          if [ -z "$value" ]; then
            echo "::error::${var,,} input is required but was blank"
            echo "Error: ${var,,} input is required but was blank" >&2
            exit 1
          fi
        done
    - name: Fetch tags
      shell: bash
      run: |
        set -euo pipefail
        git fetch --tags --force
    - name: Configure Git user
      shell: bash
      run: |
        set -euo pipefail
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Create version tag if missing
      shell: bash
      env:
        NEW: ${{ inputs.new }}
        MSG: ${{ inputs.tag_message }}
      run: |
        set -euo pipefail
        if git rev-parse -q --verify "refs/tags/$NEW" >/dev/null; then
          echo "Tag $NEW already exists; skipping creation"
        else
          MSG_USE=${MSG:-"Release $NEW"}
          git tag -a "$NEW" -m "$MSG_USE"
          git push origin "$NEW"
        fi

    - name: Update major/minor alias tags to point to new
      shell: bash
      env:
        NEW: ${{ inputs.new }}
        MAJOR: ${{ inputs.major }}
        MINOR: ${{ inputs.minor }}
      run: |
        set -euo pipefail
        # Make aliases explicitly point at the commit referenced by NEW
        COMMIT=$(git rev-parse --verify "$NEW^{commit}")
        git tag -fa "$MAJOR" -m "Alias $MAJOR -> $NEW" "$COMMIT"
        git tag -fa "$MINOR" -m "Alias $MINOR -> $NEW" "$COMMIT"
        git push origin "$MAJOR" --force
        git push origin "$MINOR" --force
