name: 'Apache Manage VHost'
description: 'Creates or updates an Apache vhost to point a domain to the Django API container. Supports reverse_proxy (default) or mod_wsgi.'

inputs:
  ssh_host:
    description: 'SSH host'
    required: true
  ssh_user:
    description: 'SSH username (non-root)'
    required: true
  ssh_key:
    description: 'SSH private key for non-root user'
    required: true
  root_ssh_key:
    description: 'SSH private key for root (optional)'
    required: false
  ssh_port:
    description: 'SSH port'
    required: false
    default: '22'
  ssh_fingerprint:
    description: 'Server SSH host key fingerprint to verify host identity (optional but recommended)'
    required: false
  podman_user:
    description: 'User on remote host (for env sourcing only)'
    required: false
    default: 'deployer'
  connect_mode:
    description: "How to connect: 'auto' (default), 'root', or 'user'"
    required: false
    default: 'root'

  # Domain selection
  domain:
    description: 'Full domain to configure. If empty, computed from base_domain + env_name + prefixes.'
    required: false
  base_domain:
    description: 'Base domain used to compute domain when domain is not provided'
    required: false
  env_name:
    description: 'Environment name for domain computation and env sourcing'
    required: false
  domain_prefix_prod:
    description: 'Prefix for production/main env'
    required: false
    default: 'app'
  domain_prefix_staging:
    description: 'Prefix for staging env'
    required: false
  domain_prefix_dev:
    description: 'Prefix for dev env'
    required: false
  require_dns_match:
    description: 'Require the domain A record to match the server public IP before applying changes'
    required: false
    default: 'true'

  # Env sourcing / port selection
  env_file_path:
    description: 'Base path to the environment file on the server (prefix); final path is ${env_file_path}${env_name}'
    required: false
  source_env:
    description: 'Source env file to derive HOST_PORT if host_port not provided'
    required: false
    default: 'true'
  host_port:
    description: 'Explicit host port to proxy to (overrides env)'
    required: false

  # VHost mode
  mode:
    description: "VHost mode: 'reverse_proxy' (default) or 'mod_wsgi'"
    required: false
    default: 'mod_wsgi'
  wsgi_script_path:
    description: 'Path to wsgi.py on server when using mod_wsgi (only for mode=mod_wsgi)'
    required: false
  server_admin:
    description: 'ServerAdmin email for Apache vhost'
    required: false
    default: 'webmaster@localhost'

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      run: |
        set -euo pipefail
        if [ -z "${{ inputs.ssh_host }}" ]; then echo 'Error: ssh_host is required' ; exit 1 ; fi
        if [ -z "${{ inputs.ssh_user }}" ]; then echo 'Error: ssh_user is required' ; exit 1 ; fi
        if [ -z "${{ inputs.ssh_key }}" ]; then echo 'Error: ssh_key is required' ; exit 1 ; fi
        case "${{ inputs.mode }}" in reverse_proxy|mod_wsgi) :;; *) echo 'Error: mode must be reverse_proxy|mod_wsgi' ; exit 1 ;;
        esac
      shell: bash

    - name: Determine Domain
      uses: uncoverthefuture-org/actions@master
      with:
        subaction: determine-domain
        params_json: |
          {
            "domain": "${{ inputs.domain }}",
            "base_domain": "${{ inputs.base_domain }}",
            "env_name": "${{ inputs.env_name }}",
            "domain_prefix_prod": "${{ inputs.domain_prefix_prod }}",
            "domain_prefix_staging": "${{ inputs.domain_prefix_staging }}",
            "domain_prefix_dev": "${{ inputs.domain_prefix_dev }}"
          }

    - name: Compute Host Port
      uses: uncoverthefuture-org/actions@master
      with:
        subaction: compute-host-port
        params_json: |
          {
            "ssh_host": "${{ inputs.ssh_host }}",
            "ssh_user": "${{ inputs.ssh_user }}",
            "ssh_key": "${{ inputs.ssh_key }}",
            "root_ssh_key": "${{ inputs.root_ssh_key }}",
            "ssh_port": "${{ inputs.ssh_port }}",
            "ssh_fingerprint": "${{ inputs.ssh_fingerprint }}",
            "podman_user": "${{ inputs.podman_user }}",
            "connect_mode": "${{ inputs.connect_mode }}",
            "env_name": "${{ inputs.env_name }}",
            "env_file_path": "${{ inputs.env_file_path }}",
            "source_env": "${{ inputs.source_env }}",
            "host_port": "${{ inputs.host_port }}"
          }

    - name: Check DNS Match
      uses: uncoverthefuture-org/actions@master
      with:
        subaction: check-dns-match
        params_json: |
          {
            "domain": "${{ inputs.domain }}",
            "require_dns_match": "${{ inputs.require_dns_match }}"
          }

    - name: Ensure Apache Installed
      uses: uncoverthefuture-org/actions@master
      with:
        subaction: ensure-apache-installed

    - name: Enable Apache Modules
      uses: uncoverthefuture-org/actions@master
      with:
        subaction: enable-apache-modules
        params_json: |
          {
            "mode": "${{ inputs.mode }}"
          }

    - name: Manage VHost Config
      uses: uncoverthefuture-org/actions@master
      with:
        subaction: manage-vhost-config
        params_json: |
          {
            "domain": "${{ inputs.domain }}",
            "host_port": "${{ inputs.host_port }}",
            "mode": "${{ inputs.mode }}",
            "wsgi_script_path": "${{ inputs.wsgi_script_path }}",
            "server_admin": "${{ inputs.server_admin }}"
          }

    - name: Enable Site and Reload
      uses: uncoverthefuture-org/actions@master
      with:
        subaction: enable-site-reload
        params_json: |
          {
            "domain": "${{ inputs.domain }}"
          }
