# ============================================================================
# ACTION: Validate Base SSH
# ============================================================================
# PURPOSE:
# Validates SSH connection parameters for app deployment actions.
# Ensures required SSH credentials and host information are provided.
#
# WHAT IT DOES:
# 1. Validates ssh_host is provided
# 2. Validates ssh_key is provided
# 3. Checks ssh_user is valid
# 4. Validates connect_mode is valid
#
# WHEN TO USE:
# - Internal validation for SSH connections
# - Validate SSH parameters
# - Part of deployment pipeline
#
# REFERENCE: See docs/ACTION_FILES_GUIDE.md for complete guide
# ============================================================================

name: 'app: validate base ssh'
description: 'Validates SSH-related inputs for app deployment.'

inputs:
  subaction:
    description: 'App subaction name.'
    required: true
  ssh_host:
    description: 'SSH host value to validate.'
    required: false
  ssh_key:
    description: 'SSH key value to validate.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Validate base SSH requirements
      shell: bash
      env:
        SUBACTION: ${{ inputs.subaction }}
        SSH_HOST: ${{ inputs.ssh_host }}
        SSH_KEY: ${{ inputs.ssh_key }}
      run: |
        set -euo pipefail
        case "$SUBACTION" in
          ssh-django-deploy|ssh-django-api-deploy|ssh-nextjs-deploy|ssh-react-deploy|ssh-laravel-deploy|write-remote-env-file)
            if [ -z "$SSH_HOST" ]; then
              echo '::error::ssh_host is required for app deployment subactions'
              echo 'Error: ssh_host is required for app deployment subactions' >&2
              exit 1
            fi
            if [ -z "$SSH_KEY" ]; then
              echo '::error::ssh_key is required for app deployment subactions'
              echo 'Error: ssh_key is required for app deployment subactions' >&2
              exit 1
            fi
            ;;
        esac
