name: 'version: update-refs'
description: 'Update @ references to the new version tag in YAML files and commit the changes.'

inputs:
  new_tag:
    description: 'New version tag (e.g., v1.2.3)'
    required: true
  force:
    description: 'Run on branch refs as well (override tag-only gating)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Skip on non-tag refs
      if: ${{ github.ref_type != 'tag' && inputs.force != 'true' }}
      shell: bash
      run: |
        echo "Skipping reference update because ref '${GITHUB_REF}' is not a tag."

    - name: Update action refs to new version
      if: ${{ github.ref_type == 'tag' || inputs.force == 'true' }}
      uses: ./.github/actions/common/replace-ref
      with:
        old_ref: '@v1.0.31'
        new_ref: ${{ format('@{0}', inputs.new_tag) }}
        patterns: |
          *.yml
          *.yaml
        exclude: |
          .github/workflows/*.yml
          .github/workflows/*.yaml

    - name: Commit version updates
      if: ${{ github.ref_type == 'tag' || inputs.force == 'true' }}
      shell: bash
      env:
        NEW_TAG: ${{ inputs.new_tag }}
      run: |
        set -euo pipefail
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update action refs to $NEW_TAG"
          git push
        fi
