name: 'version: update-refs'
description: 'Update @master references to the new version tag in YAML files and commit the changes.'

inputs:
  new_tag:
    description: 'New version tag (e.g., v1.2.3)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Update action refs to new version
      uses: ./.github/actions/common/replace-ref
      with:
        old_ref: '@master'
        new_ref: '@${{ inputs.new_tag }}'
        patterns: |
          *.yml
          *.yaml

    - name: Commit version updates
      shell: bash
      env:
        NEW_TAG: ${{ inputs.new_tag }}
      run: |
        set -euo pipefail
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update action refs to $NEW_TAG"
          git push
        fi
