# ============================================================================
# ACTION: Update References
# ============================================================================
# PURPOSE:
# Updates all @version references in YAML files to the new version tag.
# Used to update action references after releasing a new version.
#
# WHAT IT DOES:
# 1. Validates new version tag format
# 2. Finds all YAML files with @version references
# 3. Replaces old version with new version
# 4. Commits changes to repository
#
# WHEN TO USE:
# - After computing new version
# - Update action references in workflows
# - Part of release automation
#
# REFERENCE: See docs/ACTION_FILES_GUIDE.md for complete guide
# ============================================================================

name: 'version: update-refs'
description: 'Update @ references to the new version tag in YAML files and commit the changes.'

# ============================================================================
# INPUTS
# ============================================================================
inputs:
  new_tag:
    description: 'New version tag to update references to. Required. Example: v1.2.3'
    required: true
  force:
    description: 'Run on branch refs as well. Default: false. Set true to override tag-only gating'
    required: false
    default: 'false'

# ============================================================================
# EXECUTION STEPS
# ============================================================================
runs:
  using: 'composite'
  steps:
    # ========================================================================
    # STEP 1: Skip on non-tag refs
    # ========================================================================
    # Only runs on tag refs unless force=true
    # ========================================================================
    - name: Skip on non-tag refs
      if: ${{ github.ref_type != 'tag' && inputs.force != 'true' }}
      shell: bash
      run: |
        echo "Skipping reference update because ref '${GITHUB_REF}' is not a tag."

    - name: Update action refs to new version
      if: ${{ github.ref_type == 'tag' || inputs.force == 'true' }}
      uses: ./.github/actions/common/replace-ref
      with:
        old_ref: '@v1.0.53'
        new_ref: ${{ format('@{0}', inputs.new_tag) }}
        patterns: |
          *.yml
          *.yaml
        exclude: |
          .github/workflows/*.yml
          .github/workflows/*.yaml

    - name: Commit version updates
      if: ${{ github.ref_type == 'tag' || inputs.force == 'true' }}
      shell: bash
      env:
        NEW_TAG: ${{ inputs.new_tag }}
      run: |
        set -euo pipefail
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update action refs to $NEW_TAG"
          git push
        fi
