name: 'infra: request-certbot-cert'
description: 'Request or renew a Let’s Encrypt certificate using Certbot'

inputs:
  ssh_host:
    description: 'SSH host'
    required: true
  ssh_user:
    description: 'SSH username (non-root)'
    required: true
  ssh_key:
    description: 'SSH private key for non-root user'
    required: true
  root_ssh_key:
    description: 'SSH private key for root (optional)'
    required: false
  ssh_port:
    description: 'SSH port'
    required: false
    default: '22'
  ssh_fingerprint:
    description: 'Server SSH host key fingerprint'
    required: false
  connect_mode:
    description: "How to connect: 'auto' (default), 'root', or 'user'"
    required: false
    default: 'auto'
  domain:
    description: 'Primary domain to secure'
    required: true
  email:
    description: 'Email address for Certbot registration and renewal notices'
    required: true
  extra_domains:
    description: 'Comma-separated list of additional domains'
    required: false
  staging:
    description: 'Use Let’s Encrypt staging environment'
    required: false
    default: 'false'
  skip_upload:
    description: 'Skip staging/upload (assumes scripts deployed via deploy-server-scripts)'
    required: false
    default: 'true'
  show_root_install_hints:
    description: 'Show explicit manual install instructions when root privileges are required (fail-fast messaging)'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    # Probe: Check SSH reachability to avoid scp timeouts
    - name: Check SSH reachability
      id: reach
      shell: bash
      env:
        SSH_HOST: ${{ inputs.ssh_host }}
        SSH_USER: ${{ inputs.ssh_user }}
        SSH_KEY: ${{ inputs.ssh_key }}
        SSH_PORT: ${{ inputs.ssh_port }}
      run: |
        set -euo pipefail
        KEY_FILE="$(mktemp)"
        trap "rm -f '$KEY_FILE'" EXIT
        if printf '%s' "$SSH_KEY" | grep -q '\\n'; then
          printf '%s\n' "$SSH_KEY" | sed 's/\\n/\n/g' > "$KEY_FILE"
        else
          printf '%s\n' "$SSH_KEY" > "$KEY_FILE"
        fi
        chmod 600 "$KEY_FILE"
        if ssh -i "$KEY_FILE" -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=8 -p "${SSH_PORT:-22}" "$SSH_USER@$SSH_HOST" true 2>/dev/null; then
          echo "reachable=true" >> "$GITHUB_OUTPUT"
        else
          echo "reachable=false" >> "$GITHUB_OUTPUT"
        fi
    - name: Fail fast if cannot escalate for Certbot/Apache operations
      if: ${{ steps.reach.outputs.reachable == 'true' && inputs.connect_mode != 'root' }}
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ inputs.ssh_host }}
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_key }}
        port: ${{ inputs.ssh_port }}
        fingerprint: ${{ inputs.ssh_fingerprint }}
        script: |
          set -euo pipefail
          if [ "$(id -u)" -eq 0 ]; then exit 0; fi
          if command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then exit 0; fi
          if [ '${{ inputs.show_root_install_hints }}' = 'true' ]; then
            echo '::error::Certificate request/renewal (Apache plugin) requires root privileges; current session cannot escalate.' >&2
            echo "Detected: user=$(id -un); sudo(non-interactive)=no" >&2
            echo 'Install required packages and reload Apache manually on the server (as root), then re-run:' >&2
            echo '  sudo apt-get update -y' >&2
            echo '  sudo apt-get install -y software-properties-common' >&2
            echo '  sudo add-apt-repository -y ppa:certbot/certbot' >&2
            echo '  sudo apt-get update -y' >&2
            echo '  sudo apt-get install -y certbot python3-certbot-apache' >&2
            echo '  # After request, reload Apache:' >&2
            echo '  sudo systemctl reload apache2' >&2
            echo 'Or re-run this action with connect_mode: root (or provide root_ssh_key).' >&2
          else
            echo '::error::Root privileges required for certbot Apache operations.' >&2
          fi
          exit 1
    # Stage: Copy script from action path to workspace
    - name: Stage request-certbot-cert script
      if: ${{ steps.reach.outputs.reachable == 'true' && inputs.skip_upload != 'true' }}
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        WORKSPACE: ${{ github.workspace }}
      run: |
        set -euo pipefail
        mkdir -p "$WORKSPACE/.uactions_cache"
        cp "$ACTION_PATH/../../scripts/infra/request-certbot-cert.sh" "$WORKSPACE/.uactions_cache/request-certbot-cert.sh"

    # Upload: Transfer script to remote /tmp via scp
    - name: Upload request-certbot-cert script
      if: ${{ steps.reach.outputs.reachable == 'true' && inputs.skip_upload != 'true' }}
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.ssh_host }}
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_key }}
        port: ${{ inputs.ssh_port }}
        source: ".uactions_cache/request-certbot-cert.sh"
        target: "/tmp"
        overwrite: true
        timeout: 15s
        command_timeout: 30s

    # Stage: Copy wrapper script from action path to workspace
    - name: Stage request-certbot-cert-wrapper script
      if: ${{ steps.reach.outputs.reachable == 'true' && inputs.skip_upload != 'true' }}
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        WORKSPACE: ${{ github.workspace }}
      run: |
        set -euo pipefail
        mkdir -p "$WORKSPACE/.uactions_cache"
        cp "$ACTION_PATH/../../scripts/infra/request-certbot-cert-wrapper.sh" "$WORKSPACE/.uactions_cache/request-certbot-cert-wrapper.sh"

    # Upload: Transfer wrapper script to remote /tmp via scp
    - name: Upload request-certbot-cert-wrapper script
      if: ${{ steps.reach.outputs.reachable == 'true' && inputs.skip_upload != 'true' }}
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.ssh_host }}
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_key }}
        port: ${{ inputs.ssh_port }}
        source: ".uactions_cache/request-certbot-cert-wrapper.sh"
        target: "/tmp"
        overwrite: true
        timeout: 15s
        command_timeout: 30s

    # Execute: Move to $HOME/uactions/scripts/, chmod, export env, run wrapper
    - name: Execute request-certbot-cert
      uses: ./.github/actions/podman/remote-podman-exec
      with:
        ssh_host: ${{ inputs.ssh_host }}
        ssh_user: ${{ inputs.ssh_user }}
        ssh_key: ${{ inputs.ssh_key }}
        root_ssh_key: ${{ inputs.root_ssh_key }}
        ssh_port: ${{ inputs.ssh_port }}
        ssh_fingerprint: ${{ inputs.ssh_fingerprint }}
        connect_mode: ${{ inputs.connect_mode }}
        source_env: 'false'
        fail_if_env_missing: 'false'
        inline_script: |
          set -euo pipefail
          echo "🔎 SSH reachable: ${{ steps.reach.outputs.reachable }}"
          # Move wrapper script from /tmp to $HOME/uactions/scripts/
          mkdir -p "$HOME/uactions/scripts/infra"
          if [ -f /tmp/request-certbot-cert-wrapper.sh ]; then
            mv -f /tmp/request-certbot-cert-wrapper.sh "$HOME/uactions/scripts/infra/request-certbot-cert-wrapper.sh"
          fi
          chmod +x "$HOME/uactions/scripts/infra/request-certbot-cert-wrapper.sh"

          # Export inputs for server-managed script
          export DOMAIN='${{ inputs.domain }}'
          export EMAIL='${{ inputs.email }}'
          export EXTRA_DOMAINS='${{ inputs.extra_domains }}'
          export STAGING='${{ inputs.staging }}'

          # Execute wrapper script (which calls main script and reloads Apache)
          "$HOME/uactions/scripts/infra/request-certbot-cert-wrapper.sh"
