name: 'infra: install-certbot'
description: 'Install Certbot and dependencies on the remote host'

inputs:
  ssh_host:
    description: 'SSH host'
    required: true
  ssh_user:
    description: 'SSH username (non-root)'
    required: true
  ssh_key:
    description: 'SSH private key for non-root user'
    required: true
  root_ssh_key:
    description: 'SSH private key for root (optional)'
    required: false
  ssh_port:
    description: 'SSH port'
    required: false
    default: '22'
  ssh_fingerprint:
    description: 'Server SSH host key fingerprint'
    required: false
  connect_mode:
    description: "How to connect: 'auto' (default), 'root', or 'user'"
    required: false
    default: 'auto'

runs:
  using: 'composite'
  steps:
    - name: Install Certbot packages
      uses: ./.github/actions/podman/remote-podman-exec
      with:
        ssh_host: ${{ inputs.ssh_host }}
        ssh_user: ${{ inputs.ssh_user }}
        ssh_key: ${{ inputs.ssh_key }}
        root_ssh_key: ${{ inputs.root_ssh_key }}
        ssh_port: ${{ inputs.ssh_port }}
        ssh_fingerprint: ${{ inputs.ssh_fingerprint }}
        connect_mode: ${{ inputs.connect_mode }}
        source_env: 'false'
        fail_if_env_missing: 'false'
        inline_script: |
          set -euo pipefail
          if ! command -v apt-get >/dev/null 2>&1; then
            echo 'Error: Only Debian/Ubuntu apt-based systems are supported' >&2
            exit 1
          fi
          apt-get update -y
          apt-get install -y software-properties-common
          add-apt-repository -y ppa:certbot/certbot || true
          apt-get update -y
          apt-get install -y certbot python3-certbot-apache
