# ============================================================================
# ACTION: Cleanup Runner
# ============================================================================
# PURPOSE:
# Frees disk space on GitHub-hosted runners by pruning Docker and system caches.
# Prevents disk space issues during large builds.
#
# WHAT IT DOES:
# 1. Checks available disk space
# 2. If below threshold, prunes Docker images and containers
# 3. Clears package manager caches
# 4. Removes unnecessary files
#
# WHEN TO USE:
# - Before large Docker builds
# - When disk space is limited
# - Part of build optimization
#
# REFERENCE: See docs/ACTION_FILES_GUIDE.md for complete guide
# ============================================================================

name: 'common: cleanup-runner'
description: 'Free disk space on GitHub-hosted runners by pruning Docker and system caches when space is low.'

# ============================================================================
# INPUTS
# ============================================================================
inputs:
  min_free_gb:
    description: 'Minimum free disk space threshold in GiB. Default: 5. Use 0 to always run cleanup'
    required: false
    default: '5'

# ============================================================================
# EXECUTION STEPS
# ============================================================================
runs:
  using: 'composite'
  steps:
    # ========================================================================
    # STEP 1: Check and clean disk space
    # ========================================================================
    # Checks available space and cleans if below threshold
    # ========================================================================
    - name: Check and clean disk space
      shell: bash
      env:
        MIN_FREE_GB: ${{ inputs.min_free_gb }}
      run: |
        set -euo pipefail

        required_free="${MIN_FREE_GB:-10}"
        if ! [[ "$required_free" =~ ^[0-9]+$ ]]; then
          echo "Invalid min_free_gb '$required_free'; defaulting to 10" >&2
          required_free=10
        fi

        echo "::group::Disk usage before cleanup"
        df -h
        echo "::endgroup::"

        free_gb=$(df --output=avail -BG / | tail -n1 | tr -dc '0-9')
        echo "Available GiB before cleanup: $free_gb"

        if [ "$required_free" -gt 0 ] && [ "$free_gb" -ge "$required_free" ]; then
          echo "Sufficient disk space ($free_gb GiB >= $required_free GiB); skipping cleanup."
          exit 0
        fi

        echo "Running cleanup (threshold: ${required_free} GiB)."

        echo "Pruning Docker system..."
        docker system prune -af || true
        docker volume prune -f || true

        echo "Cleaning apt cache..."
        sudo apt-get clean || true
        sudo apt-get autoremove -y || true

        echo "Removing temporary files..."
        sudo rm -rf /tmp/* || true

        echo "::group::Disk usage after cleanup"
        df -h
        echo "::endgroup::"
