name: 'common: route category'
description: 'Determines the dispatcher category for a given subaction.'

inputs:
  subaction:
    description: 'Subaction to route'
    required: false
  category:
    description: 'Optional explicit category override'
    required: false

outputs:
  category:
    description: 'Resolved category (build|podman|infra|app|version)'
    value: ${{ steps.route.outputs.category }}

runs:
  using: 'composite'
  steps:
    - name: Route
      id: route
      shell: bash
      env:
        SA: ${{ inputs.subaction }}
        CAT: ${{ inputs.category }}
        ROUTES_FILE: ${{ github.action_path }}/routes.json
      run: |
        set -euo pipefail
        python3 "$GITHUB_ACTION_PATH/router.py"
