name: 'infra: probe-host-capabilities'
description: 'Probe host for installed packages, services, listeners, and Traefik mode without making changes.'

outputs:
  has_podman:
    description: 'true if podman is installed'
    value: ${{ steps.probe.outputs.has_podman }}
  podman_version:
    description: 'podman --version output or empty'
    value: ${{ steps.probe.outputs.podman_version }}
  has_apache:
    description: 'true if apache2 package/service present'
    value: ${{ steps.probe.outputs.has_apache }}
  has_nginx:
    description: 'true if nginx package/service present'
    value: ${{ steps.probe.outputs.has_nginx }}
  has_ufw:
    description: 'true if ufw present'
    value: ${{ steps.probe.outputs.has_ufw }}
  has_webmin:
    description: 'true if webmin package present'
    value: ${{ steps.probe.outputs.has_webmin }}
  has_usermin:
    description: 'true if usermin package present'
    value: ${{ steps.probe.outputs.has_usermin }}
  listen_80:
    description: 'true if TCP 80 has a listener'
    value: ${{ steps.probe.outputs.listen_80 }}
  listen_443:
    description: 'true if TCP 443 has a listener'
    value: ${{ steps.probe.outputs.listen_443 }}
  traefik_mode:
    description: 'none|container|quadlet (best-effort)'
    value: ${{ steps.probe.outputs.traefik_mode }}

inputs:
  ssh_host:
    required: true
  ssh_user:
    required: true
  ssh_key:
    required: true
  ssh_port:
    required: false
    default: '22'
  ssh_fingerprint:
    required: false

runs:
  using: 'composite'
  steps:
    - name: Probe host (SSH and set outputs)
      id: probe
      shell: bash
      env:
        SSH_HOST: ${{ inputs.ssh_host }}
        SSH_USER: ${{ inputs.ssh_user }}
        SSH_KEY: ${{ inputs.ssh_key }}
        SSH_PORT: ${{ inputs.ssh_port }}
      run: |
        set -euo pipefail
        KEY_FILE="$(mktemp)"
        trap "rm -f '$KEY_FILE'" EXIT
        if printf '%s' "$SSH_KEY" | grep -q '\n'; then
          printf '%s\n' "$SSH_KEY" | sed 's/\\n/\n/g' > "$KEY_FILE"
        else
          printf '%s\n' "$SSH_KEY" > "$KEY_FILE"
        fi
        chmod 600 "$KEY_FILE"

        read -r -d '' REMOTE_SCRIPT <<'RS'
        set -euo pipefail
        bool() { [ "$1" -eq 0 ] && echo true || echo false; }

        HAS_PODMAN=false
        PV=""
        if command -v podman >/dev/null 2>&1; then
          HAS_PODMAN=true
          PV=$(podman --version 2>/dev/null || true)
        fi

        dpkgq() { dpkg -s "$1" >/dev/null 2>&1 || dpkg-query -W -f='${Status}' "$1" 2>/dev/null | grep -q installed; }
        HAS_APACHE=false
        if dpkgq apache2 || systemctl is-enabled apache2 >/dev/null 2>&1 || systemctl is-active apache2 >/dev/null 2>&1; then HAS_APACHE=true; fi
        HAS_NGINX=false
        if dpkgq nginx || systemctl is-enabled nginx >/dev/null 2>&1 || systemctl is-active nginx >/dev/null 2>&1; then HAS_NGINX=true; fi

        HAS_UFW=false
        if command -v ufw >/dev/null 2>&1; then HAS_UFW=true; fi

        HAS_WEBMIN=false
        if dpkg -s webmin >/dev/null 2>&1; then HAS_WEBMIN=true; fi

        HAS_USERMIN=false
        if dpkg -s usermin >/dev/null 2>&1; then HAS_USERMIN=true; fi

        listen() {
          local port="$1"
          if ss -ltnH 2>/dev/null | awk '{print $4}' | grep -qE "(^|:)$port$"; then return 0; fi
          return 1
        }
        L80=$(bool $(listen 80; echo $?))
        L443=$(bool $(listen 443; echo $?))

        # Traefik mode detection
        TMODE=none
        if command -v podman >/dev/null 2>&1 && podman container exists traefik >/dev/null 2>&1; then
          TMODE=container
        fi
        if command -v systemctl >/dev/null 2>&1; then
          if systemctl --user is-enabled --quiet http.socket 2>/dev/null || systemctl --user is-enabled --quiet https.socket 2>/dev/null; then
            TMODE=quadlet
          fi
        fi

        printf '%s\n' \
          "has_podman=$HAS_PODMAN" \
          "podman_version=$PV" \
          "has_apache=$HAS_APACHE" \
          "has_nginx=$HAS_NGINX" \
          "has_ufw=$HAS_UFW" \
          "has_webmin=$HAS_WEBMIN" \
          "has_usermin=$HAS_USERMIN" \
          "listen_80=$L80" \
          "listen_443=$L443" \
          "traefik_mode=$TMODE"
        RS

        OUT=$(ssh -i "$KEY_FILE" -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=8 -p "${SSH_PORT:-22}" "$SSH_USER@$SSH_HOST" "bash -s" <<< "$REMOTE_SCRIPT" 2>/dev/null || true)
        # Write parsed lines to GITHUB_OUTPUT
        while IFS= read -r line; do
          case "$line" in
            has_podman=*|podman_version=*|has_apache=*|has_nginx=*|has_ufw=*|has_webmin=*|has_usermin=*|listen_80=*|listen_443=*|traefik_mode=*)
              echo "$line" >> "$GITHUB_OUTPUT" ;;
          esac
        done <<< "$OUT"
