name: 'django: validate'
description: 'Validate inputs for SSH Django deploy with sensible defaults.'

inputs:
  ssh_host:
    required: true
  ssh_key:
    required: true
  registry:
    required: false
    default: 'ghcr.io'
  registry_login:
    required: false
    default: 'true'
  registry_username:
    required: false
  registry_token:
    required: false
  write_env_file:
    required: false
    default: 'false'
  env_b64:
    required: false
  env_content:
    required: false
  image_name:
    required: false

runs:
  using: 'composite'
  steps:
    - name: Validate
      shell: bash
      run: |
        set -euo pipefail
        if [ -z "${{ inputs.ssh_host }}" ]; then echo 'Error: ssh_host is required' ; exit 1 ; fi
        if [ -z "${{ inputs.ssh_key }}" ]; then echo 'Error: ssh_key is required' ; exit 1 ; fi
        # Only enforce creds for non-GHCR when registry_login=true
        if [ "${{ inputs.registry_login }}" = "true" ] && [ "${{ inputs.registry }}" != "ghcr.io" ]; then
          if [ -z "${{ inputs.registry_username }}" ] || [ -z "${{ inputs.registry_token }}" ]; then
            echo 'Error: registry_username and registry_token are required for non-GHCR registries when registry_login=true' ; exit 1
          fi
        fi
        if [ "${{ inputs.write_env_file }}" = "true" ]; then
          if [ -z "${{ inputs.env_b64 }}" ] && [ -z "${{ inputs.env_content }}" ]; then
            echo 'Error: write_env_file=true but neither env_b64 nor env_content provided' ; exit 1
          fi
        fi
