# ============================================================================
# ACTION: Compute Next Version
# ============================================================================
# PURPOSE:
# Calculates the next semantic version based on existing git tags.
# Supports patch, minor, and major version bumps.
#
# WHAT IT DOES:
# 1. Fetches all git tags
# 2. Finds the latest semantic version tag
# 3. Bumps version based on level (patch|minor|major)
# 4. Returns new version and version aliases
#
# WHEN TO USE:
# - Automatic version bumping in CI/CD
# - Semantic versioning workflows
# - Release automation
#
# OUTPUTS:
# - new: Full new version (e.g., v1.0.1)
# - major: Major alias (e.g., v1)
# - minor: Minor alias (e.g., v1.0)
# - last: Previous version (e.g., v1.0.0)
#
# REFERENCE: See docs/ACTION_FILES_GUIDE.md for complete guide
# ============================================================================

name: 'version: compute-next'
description: 'Compute next semver (vX.Y.Z) from existing tags, with bump level (patch|minor|major). Outputs new, major alias vX, minor alias vX.Y, and last.'

# ============================================================================
# INPUTS
# ============================================================================
inputs:
  level:
    description: 'Bump level for semantic versioning. Default: patch. Options: patch (1.0.0→1.0.1), minor (1.0.0→1.1.0), major (1.0.0→2.0.0)'
    required: false
    default: 'patch'

# ============================================================================
# OUTPUTS
# ============================================================================
outputs:
  new:
    description: 'New computed semantic version tag. Example: v1.0.1'
    value: ${{ steps.calc.outputs.new }}
  major:
    description: 'Major version alias for tagging. Example: v1'
    value: ${{ steps.calc.outputs.major }}
  minor:
    description: 'Minor version alias for tagging. Example: v1.0'
    value: ${{ steps.calc.outputs.minor }}
  last:
    description: 'Previous full version tag. Example: v1.0.0. Empty if no previous tags'
    value: ${{ steps.calc.outputs.last }}

# ============================================================================
# EXECUTION STEPS
# ============================================================================
runs:
  using: 'composite'
  steps:
    # ========================================================================
    # STEP 1: Validate level
    # ========================================================================
    # Ensures bump level is one of: patch, minor, major
    # ========================================================================
    - name: Validate level
      shell: bash
      run: |
        set -euo pipefail
        case "${{ inputs.level }}" in patch|minor|major) :;; *) echo '::error::level must be patch|minor|major'; echo 'Error: level must be patch|minor|major' >&2; exit 1;; esac

    - name: Fetch tags
      shell: bash
      run: |
        set -euo pipefail
        git fetch --tags --force

    - name: Compute next version
      id: calc
      shell: bash
      env:
        LEVEL: ${{ inputs.level }}
      run: |
        set -euo pipefail
        LAST=$(git tag -l 'v[0-9]*.[0-9]*.[0-9]*' | sed 's/^v//' | sort -V | tail -n1 || true)
        if [ -z "$LAST" ]; then
          MAJ=1; MIN=0; PAT=0
        else
          IFS=. read -r MAJ MIN PAT <<EOF
        $LAST
        EOF
          case "$LEVEL" in
            major) MAJ=$((MAJ+1)); MIN=0; PAT=0;;
            minor) MIN=$((MIN+1)); PAT=0;;
            *) PAT=$((PAT+1));;
          esac
        fi
        NEW="v${MAJ}.${MIN}.${PAT}"
        echo "new=$NEW" >> "$GITHUB_OUTPUT"
        echo "major=v${MAJ}" >> "$GITHUB_OUTPUT"
        echo "minor=v${MAJ}.${MIN}" >> "$GITHUB_OUTPUT"
        echo "last=${LAST:+v$LAST}" >> "$GITHUB_OUTPUT"
