name: 'infra: install-podman'
description: 'Install Podman and dependencies on Ubuntu/Debian host'

inputs:
  ssh_host:
    description: 'SSH host'
    required: true
  ssh_user:
    description: 'SSH username (non-root)'
    required: true
  ssh_key:
    description: 'SSH private key for non-root user'
    required: true
  ssh_port:
    description: 'SSH port'
    required: false
    default: '22'
  ssh_fingerprint:
    description: 'Server SSH host key fingerprint'
    required: false
  additional_packages:
    description: 'Additional packages to install with podman'
    required: false
  skip_upload:
    description: 'Skip staging/upload (assumes scripts deployed via deploy-server-scripts)'
    required: false
    default: 'true'
  show_root_install_hints:
    description: 'Show explicit manual install instructions when root privileges are required'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    # Probe: Check SSH reachability to avoid scp timeouts
    - name: Check SSH reachability
      id: reach
      shell: bash
      env:
        SSH_HOST: ${{ inputs.ssh_host }}
        SSH_USER: ${{ inputs.ssh_user }}
        SSH_KEY: ${{ inputs.ssh_key }}
        SSH_PORT: ${{ inputs.ssh_port }}
      run: |
        set -euo pipefail
        KEY_FILE="$(mktemp)"
        trap "rm -f '$KEY_FILE'" EXIT
        if printf '%s' "$SSH_KEY" | grep -q '\\n'; then
          printf '%s\n' "$SSH_KEY" | sed 's/\\n/\n/g' > "$KEY_FILE"
        else
          printf '%s\n' "$SSH_KEY" > "$KEY_FILE"
        fi
        chmod 600 "$KEY_FILE"
        if ssh -i "$KEY_FILE" -o BatchMode=yes -o StrictHostKeyChecking=no -o ConnectTimeout=8 -p "${SSH_PORT:-22}" "$SSH_USER@$SSH_HOST" true 2>/dev/null; then
          echo "reachable=true" >> "$GITHUB_OUTPUT"
        else
          echo "reachable=false" >> "$GITHUB_OUTPUT"
        fi
    # Stage: Copy script from action path to workspace (needed for scp)
    - name: Stage install-podman script
      if: ${{ steps.reach.outputs.reachable == 'true' && inputs.skip_upload != 'true' }}
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        WORKSPACE: ${{ github.workspace }}
      run: |
        set -euo pipefail
        mkdir -p "$WORKSPACE/.uactions_cache"
        cp "$ACTION_PATH/../../scripts/infra/install-podman.sh" "$WORKSPACE/.uactions_cache/install-podman.sh"

    # Upload: Transfer script to remote /tmp via scp
    - name: Upload install-podman script
      if: ${{ steps.reach.outputs.reachable == 'true' && inputs.skip_upload != 'true' }}
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ inputs.ssh_host }}
        username: ${{ inputs.ssh_user }}
        key: ${{ inputs.ssh_key }}
        port: ${{ inputs.ssh_port }}
        source: ".uactions_cache/install-podman.sh"
        target: "/tmp"
        overwrite: true
        timeout: 15s
        command_timeout: 30s

    - name: Execute install-podman
      if: ${{ steps.reach.outputs.reachable == 'true' }}
      uses: ./.github/actions/podman/remote-podman-exec
      with:
        ssh_host: ${{ inputs.ssh_host }}
        ssh_user: ${{ inputs.ssh_user }}
        ssh_key: ${{ inputs.ssh_key }}
        ssh_port: ${{ inputs.ssh_port }}
        ssh_fingerprint: ${{ inputs.ssh_fingerprint }}
        source_env: 'false'
        fail_if_env_missing: 'false'
        inline_script: |
          set -euo pipefail
          if [ "$(id -u)" -ne 0 ]; then
            if [ "${{ inputs.show_root_install_hints }}" = "true" ]; then
              SUDO_AVAIL=no
              if command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then SUDO_AVAIL=yes; fi
              echo '::error::Host preparation requires root privileges to install packages (podman missing).' >&2
              echo "Detected: user=$(id -un); sudo(non-interactive)=${SUDO_AVAIL}" >&2
              echo 'To install manually on the server (as root), run:' >&2
              echo '  sudo apt-get update -y' >&2
              echo '  sudo apt-get install -y podman curl jq ca-certificates' >&2
              echo 'Then re-run this workflow, or connect as root for automatic installation.' >&2
            else
              echo '::error::install-podman requires root privileges.' >&2
            fi
            exit 1
          fi
          mkdir -p "$HOME/uactions/scripts/infra"
          if [ -f /tmp/install-podman.sh ]; then
            mv -f /tmp/install-podman.sh "$HOME/uactions/scripts/infra/install-podman.sh"
          fi
          chmod +x "$HOME/uactions/scripts/infra/install-podman.sh"

          export ADDITIONAL_PACKAGES='${{ inputs.additional_packages }}'
          "$HOME/uactions/scripts/infra/install-podman.sh"
