# ============================================================================
# ACTION: Operation Summary
# ============================================================================
# PURPOSE:
# Generates a detailed summary of the operation after execution.
# Displays results, status, and troubleshooting information.
#
# WHAT IT DOES:
# 1. Collects outcomes from all dispatchers (build, app, podman, infra, version, common)
# 2. Routes to category-specific summary generator
# 3. Compiles overall operation summary
# 4. Displays success/failure status
# 5. Provides troubleshooting guidance
#
# WHEN TO USE:
# - Internal action called by main aggregator
# - Generates summary after operation completes
# - Provides user-friendly output and next steps
#
# OUTPUTS:
# - Detailed operation summary
# - Success/failure status
# - Links to logs and workflow run
# - Troubleshooting guidance
#
# REFERENCE: See docs/ACTION_FILES_GUIDE.md for complete guide
# ============================================================================

name: 'common: operation-summary'
description: 'Generates a detailed summary of the operation, including results, failures, and where to find errors.'

# ============================================================================
# INPUTS - Operation results from all dispatchers
# ============================================================================
inputs:
  subaction:
    description: 'The subaction that was run'
    required: true
  category:
    description: 'The category of the subaction'
    required: true
  build_outcome:
    description: 'Outcome of the build dispatch step'
    required: false
    default: 'skipped'
  build_env_name:
    description: 'Environment name from build'
    required: false
  build_image_tag:
    description: 'Image tag from build'
    required: false
  build_deploy_enabled:
    description: 'Deploy enabled from build'
    required: false
  build_env_key:
    description: 'Environment key from build'
    required: false
  podman_outcome:
    description: 'Outcome of podman dispatch'
    required: false
    default: 'skipped'
  infra_outcome:
    description: 'Outcome of infra dispatch'
    required: false
    default: 'skipped'
  app_outcome:
    description: 'Outcome of app dispatch'
    required: false
    default: 'skipped'
  version_outcome:
    description: 'Outcome of version dispatch'
    required: false
    default: 'skipped'
  version_new:
    description: 'New version from version dispatch'
    required: false
  version_major:
    description: 'Major version from version dispatch'
    required: false
  version_minor:
    description: 'Minor version from version dispatch'
    required: false
  version_last:
    description: 'Last version from version dispatch'
    required: false
  common_outcome:
    description: 'Outcome of common dispatch'
    required: false
    default: 'skipped'
  common_secret_name:
    description: 'Secret resolved by common dispatch'
    required: false
  common_secret_found:
    description: 'Whether the secret existed (true/false)'
    required: false
  common_env_b64:
    description: 'Base64-encoded env payload from common dispatch (not displayed)'
    required: false
  common_env_name:
    description: 'Environment name from common dispatch'
    required: false
  common_env_key:
    description: 'Environment key from common dispatch'
    required: false
  common_deploy_enabled:
    description: "Deploy flag from common dispatch ('true' or 'false')"
    required: false
  common_image_tag:
    description: 'Image tag from common dispatch'
    required: false
  common_env_file:
    description: 'Path to decoded env file written by common dispatch'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Ensure bundled actions
      uses: ./.github/actions/common/ensure-bundled-actions

    - name: Build Summary
      id: build_sum
      if: ${{ inputs.category == 'build' }}
      uses: ./.github/actions/common/operation-summary/build
      with:
        outcome: ${{ inputs.build_outcome }}
        env_name: ${{ inputs.build_env_name }}
        image_tag: ${{ inputs.build_image_tag }}
        deploy_enabled: ${{ inputs.build_deploy_enabled }}
        env_key: ${{ inputs.build_env_key }}

    - name: Podman Summary
      id: podman_sum
      if: ${{ inputs.category == 'podman' }}
      uses: ./.github/actions/common/operation-summary/podman
      with:
        outcome: ${{ inputs.podman_outcome }}

    - name: Infra Summary
      id: infra_sum
      if: ${{ inputs.category == 'infra' }}
      uses: ./.github/actions/common/operation-summary/infra
      with:
        outcome: ${{ inputs.infra_outcome }}

    - name: App Summary
      id: app_sum
      if: ${{ inputs.category == 'app' }}
      uses: ./.github/actions/common/operation-summary/app
      with:
        outcome: ${{ inputs.app_outcome }}

    - name: Version Summary
      id: version_sum
      if: ${{ inputs.category == 'version' }}
      uses: ./.github/actions/common/operation-summary/version
      with:
        outcome: ${{ inputs.version_outcome }}
        new: ${{ inputs.version_new }}
        major: ${{ inputs.version_major }}
        minor: ${{ inputs.version_minor }}
        last: ${{ inputs.version_last }}

    # ========================================================================
    # STEP 2: Generate Overall Summary
    # ========================================================================
    # Compiles results from category-specific summaries
    # Displays success/failure status and troubleshooting guidance
    # ========================================================================
    - name: Generate Overall Summary
      shell: bash
      env:
        COMMON_OUTCOME: ${{ inputs.common_outcome }}
        COMMON_SECRET_NAME: ${{ inputs.common_secret_name }}
        COMMON_SECRET_FOUND: ${{ inputs.common_secret_found }}
        COMMON_ENV_B64: ${{ inputs.common_env_b64 }}
        COMMON_ENV_NAME: ${{ inputs.common_env_name }}
        COMMON_ENV_KEY: ${{ inputs.common_env_key }}
        COMMON_DEPLOY_ENABLED: ${{ inputs.common_deploy_enabled }}
        COMMON_IMAGE_TAG: ${{ inputs.common_image_tag }}
        COMMON_ENV_FILE: ${{ inputs.common_env_file }}
      run: |
        # Enable strict error handling
        set -euo pipefail

        # Extract operation details
        SUBACTION="${{ inputs.subaction }}"
        CATEGORY="${{ inputs.category }}"
        TIMESTAMP="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"

        # Route to category-specific summary or use common summary
        # Each category has its own summary generator that formats results
        case "$CATEGORY" in
          build)
            # Get build summary from build-specific summary generator
            SUMMARY="${{ steps.build_sum.outputs.summary }}"
            SUCCESS="${{ steps.build_sum.outputs.success }}"
            ;;
          podman)
            # Get podman summary from podman-specific summary generator
            SUMMARY="${{ steps.podman_sum.outputs.summary }}"
            SUCCESS="${{ steps.podman_sum.outputs.success }}"
            ;;
          infra)
            # Get infrastructure summary from infra-specific summary generator
            SUMMARY="${{ steps.infra_sum.outputs.summary }}"
            SUCCESS="${{ steps.infra_sum.outputs.success }}"
            ;;
          app)
            # Get app deployment summary from app-specific summary generator
            SUMMARY="${{ steps.app_sum.outputs.summary }}"
            SUCCESS="${{ steps.app_sum.outputs.success }}"
            ;;
          version)
            # Get version summary from version-specific summary generator
            SUMMARY="${{ steps.version_sum.outputs.summary }}"
            SUCCESS="${{ steps.version_sum.outputs.success }}"
            ;;
          common)
            # Format common utility results
            SECRET_NAME="${COMMON_SECRET_NAME:-n/a}"
            SECRET_FOUND="${COMMON_SECRET_FOUND:-unknown}"
            ENV_NAME_VAL="${COMMON_ENV_NAME:-n/a}"
            ENV_KEY_VAL="${COMMON_ENV_KEY:-n/a}"
            DEPLOY_VAL="${COMMON_DEPLOY_ENABLED:-unknown}"
            IMAGE_TAG_VAL="${COMMON_IMAGE_TAG:-n/a}"
            ENV_FILE_VAL="${COMMON_ENV_FILE:-n/a}"
            
            # Build markdown summary for common utilities
            SUMMARY="### 🧩 Common Utility
            - **Env name**: ${ENV_NAME_VAL}
            - **Env key**: ${ENV_KEY_VAL}
            - **Deploy enabled**: ${DEPLOY_VAL}
            - **Image tag**: ${IMAGE_TAG_VAL}
            - **Secret key**: ${SECRET_NAME}
            - **Secret found**: ${SECRET_FOUND}
            - **Env file**: ${ENV_FILE_VAL}"
            
            # Determine success based on outcome
            if [ "${COMMON_OUTCOME}" = "success" ]; then
              SUCCESS="true"
            else
              SUCCESS="false"
            fi
            ;;
          *)
            # Handle unknown category
            SUMMARY="### ❓ Unknown Operation
            **Status**: ⚠️ Unknown category"
            SUCCESS="false"
            ;;
        esac

        # Print header with operation details
        echo "## 🔍 Uncover Actions Detailed Summary"
        echo ""
        echo "### 📋 Operation Overview"
        echo "- **Subaction**: $SUBACTION"
        echo "- **Category**: $CATEGORY"
        echo "- **Timestamp**: $TIMESTAMP"
        echo "- **Workflow Run**: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        echo ""
        
        # Print category-specific summary
        echo "$SUMMARY"
        echo ""

        # Print overall status and next steps or troubleshooting
        echo "### 📊 Overall Status"
        if [ "$SUCCESS" = "true" ]; then
          # Success case: show completion message and next steps
          echo "**Result**: ✅ Operation completed successfully"
          echo "**Next Steps**: Monitor the deployed application or proceed with related workflows."
        else
          # Failure case: show error and troubleshooting guidance
          echo "**Result**: ❌ Operation failed"
          echo "**Troubleshooting**:"
          echo "  - Review the job logs for the failed step"
          echo "  - Check GitHub Actions run: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo "  - Verify input parameters and secrets"
          echo "  - Ensure remote hosts are accessible and properly configured"
          exit 1
        fi
