name: Release — Auto Version Tags

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      level:
        description: 'Semver bump level to apply (default: patch)'
        required: false
        default: patch
        type: choice
        options: [patch, minor, major]

permissions:
  contents: write

concurrency:
  group: auto-versioning
  cancel-in-progress: false

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint action uses
        uses: uncoverthefuture-org/actions/.github/actions/common/lint-uses@master
        with:
          allow_deep_repo: 'true'

      - name: Compute next version
        id: ver
        uses: uncoverthefuture-org/actions/.github/actions/version/dispatch@master
        with:
          subaction: compute-next
          params_json: |
            {
              "level": "${{ github.event.inputs.level || 'patch' }}"
            }

      - name: Update action refs to new version
        uses: uncoverthefuture-org/actions/.github/actions/version/dispatch@master
        with:
          subaction: update-refs
          params_json: |
            {
              "new_tag": "${{ steps.ver.outputs.new }}"
            }

      - name: Create version tag and update aliases
        uses: uncoverthefuture-org/actions/.github/actions/version/dispatch@master
        with:
          subaction: update-tags
          params_json: |
            {
              "new": "${{ steps.ver.outputs.new }}",
              "major": "${{ steps.ver.outputs.major }}",
              "minor": "${{ steps.ver.outputs.minor }}",
              "tag_message": "Release ${{ steps.ver.outputs.new }}"
            }
