name: Release — Auto Version Tags

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      level:
        description: 'Semver bump level to apply (default: patch)'
        required: false
        default: patch
        type: choice
        options: [patch, minor, major]

permissions:
  contents: write

concurrency:
  group: auto-versioning
  cancel-in-progress: false

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint action uses
        run: |
          echo "Checking for forbidden uses..."
          # Check for relative uses outside version actions
          REL_FILES=$(find . -name "*.yml" -o -name "*.yaml" | grep -v action.yml | xargs grep -lE "^[[:space:]]*uses:[[:space:]]+\./\.github/actions/" | grep -v auto-version.yml | grep -v version/compute-next | grep -v version/update-tags || true)
          if [ -n "$REL_FILES" ]; then
            echo "Error: Found relative uses in: $REL_FILES" >&2
            exit 1
          fi
          # Check for deep repo uses
          DEEP_FILES=$(find . -name "*.yml" -o -name "*.yaml" | grep -v README.md | xargs grep -lE "^[[:space:]]*uses:[[:space:]]+uncoverthefuture-org/actions/\.github/actions/" || true)
          if [ -n "$DEEP_FILES" ]; then
            echo "Error: Found deep repo uses in: $DEEP_FILES" >&2
            exit 1
          fi
          echo "Lint passed."

      - name: Compute next version
        id: ver
        uses: uncoverthefuture-org/actions@master
        with:
          subaction: compute-next
          params_json: |
            {
              "level": "${{ github.event.inputs.level || 'patch' }}"
            }

      - name: Update action refs to new version
        uses: uncoverthefuture-org/actions@master
        with:
          subaction: update-refs
          params_json: |
            {
              "new_tag": "${{ steps.ver.outputs.new }}"
            }

      - name: Create version tag and update aliases
        uses: uncoverthefuture-org/actions@master
        with:
          subaction: update-tags
          params_json: |
            {
              "new": "${{ steps.ver.outputs.new }}",
              "major": "${{ steps.ver.outputs.major }}",
              "minor": "${{ steps.ver.outputs.minor }}",
              "tag_message": "Release ${{ steps.ver.outputs.new }}"
            }
