name: Release — Auto Version Tags

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      level:
        description: 'Semver bump level to apply (default: patch)'
        required: false
        default: patch
        type: choice
        options: [patch, minor, major]

permissions:
  contents: write

concurrency:
  group: auto-versioning
  cancel-in-progress: false

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute next version
        id: ver
        uses: ./.github/actions/version/compute-next
        with:
          level: ${{ github.event.inputs.level || 'patch' }}

      - name: Create version tag and update aliases
        uses: ./.github/actions/version/update-tags
        with:
          new: ${{ steps.ver.outputs.new }}
          major: ${{ steps.ver.outputs.major }}
          minor: ${{ steps.ver.outputs.minor }}
          tag_message: Release ${{ steps.ver.outputs.new }}
